name: products
description: Products.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP
  dio: ^5.3.0

  # General
  equatable: ^2.0.5
  google_fonts: ^5.1.0

  # Storage
  shared_preferences: ^2.2.0

  # Modular
  flutter_modular: ^5.0.3

  # Test
  mocktail: ^0.3.0
  mockito: ^5.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  modular_test: ^2.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/
